# Generated by Django 5.0 on 2025-09-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(upload_to='hero_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('primaryBtn', models.CharField(default='ShopNow', max_length=100)),
                ('primaryBtnLink', models.URLField(blank=True, null=True)),
                ('secondaryBtn', models.CharField(default='ContactUs', max_length=100)),
                ('secondaryBtnLink', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped')], default='Pending', max_length=20),
        ),
    ]
